### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BuzzardM**
fixed readme

### CODE REVIEW

**Comment by BuzzardM** [comment]
@Jelledb thoughts??

**Comment by KoenLemmen** [comment]
I'm missing

**Comment by BuzzardM** [comment]
Fixed it @KoenLemmen

**Comment by KoenLemmen** [comment]
HUTS, time to merge @Jelledb

**Comment by Jelledb** [comment]
Thanks, @BuzzardM @KoenLemmen for your contributions. This is highly appreciated!

**Pull request merged**
